export const CREATE_POST = 'CREATE_POST'; // 相应创建帖子的常量
export const POST_SUCCESS = 'POST_SUCCESS'; // 设置处理帖子逻辑成功信息
export const POSTS_SUCCESS = 'POSTS_SUCCESS'; // 设置处理帖子列表逻辑成功信息
export const POST_ERROR = 'POST_ERROR'; // 设置处理帖子逻辑失败信息
export const SET_POSTS = 'SET_POSTS'; // 将新帖子添加到 Redux Store
export const GET_POSTS = 'GET_POSTS'; // 获取帖子列表
export const GET_POST = 'GET_POST'; // 获取帖子
export const SET_POST = 'SET_POST'; // 更新帖子
export const POST_NORMAL = 'POST_NORMAL';
export const UPDATE_POSTS = 'UPDATE_POSTS'; // 清空帖子